### ISSUE TITLE
Support for ethers@6

### ISSUE THREAD

**Issue by ChengZicy** [vu3th/vue-dapp#138]
When installing ethers@6, errors below occurred
```
 Missing "./lib/utils" specifier in "ethers" package [plugin vite:dep-pre-bundle]
```
Downgrading to ethers@5.6.8 solves this problem

Wonder if it will support ethers@6 or not

**Comment by chnejohnson** [comment]
@ChengZicy Okay, I will prepare for it

**Comment by chnejohnson** [comment]
@ChengZicy Now you can try installing vue-dapp@v0.10.0 with ethers@6.6.3. Alternatively, you can try using the [vue3-dapp-starter branch ethers-v6](https://github.com/vu3th/vue3-dapp-starter/tree/ethers-v6). Due to significant changes in ethers v6, some issues may arise. It is recommended to reproduce the problem in vue3-dapp-starter, so I can address the upgrade issues more efficiently.

**Comment by chnejohnson** [comment]
Now vue-dapp supports ethers v6
