### ISSUE TITLE
Pinia error when using in a composable

### ISSUE THREAD

**Issue by coxlr** [vu3th/vue-dapp#160]
I am trying to use this in a composable but am getting the following error from pinia.

<img width="571" alt="Screenshot 2024-04-14 at 9 05 19 AM" src="https://github.com/vu3th/vue-dapp/assets/8451762/0a978854-d727-46c6-b721-56382f54c7ad">

I have updated the vue-dapp-starter to show an example of what I am trying to do, which reproduces the error. Am I missing something here, or is there anything I need to do differently to get this to work in this way?

https://github.com/coxlr/vue-dapp-starter

**Comment by johnson86tw** [comment]
The issue arises here because Pinia initializes after the app is mounted. Therefore, when you use `useVueDapp` or any functions within it, ensure that they are executed after Vue has initialized.

https://github.com/coxlr/vue-dapp-starter/blob/e480613bb680a0323cec1e7e65cf0a2d95b09456/src/composables/useWallet.ts#L5-L24

You can do it like this

```ts
export default function useWallet() {
	const { status, isConnected, address, chainId, error, disconnect, connectTo, addConnectors } = useVueDapp()

	function init() {
		addConnectors([
			...
		])
	}

```

Then in App.vue

```ts
const { init } = useWallet()
init()
```

**Comment by coxlr** [comment]
Thank you for detailed explanation, I have followed your instructions and got it all working as expected now. Thank you!

**Comment by johnson86tw** [comment]
@coxlr You're welcome :)
